### ISSUE TITLE
Unanticipated behavior for the element `code` when displayed inline

### ISSUE THREAD

**Issue by nalmeida** [5t3ph/11ty-netlify-jumpstart#1]
I have noticed an unanticipated behavior / display for the element `code` when displayed inline (print). I have tested it on a Mac OS High Sierra.

Firefox: 76.0.1 (64-bit)
Chrome: Version 80.0.3987.163 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/200209/82816085-e0026300-9e70-11ea-9944-e23c2e8debc6.png)

**Comment by 5t3ph** [comment]
@nalmeida I pushed an update that may resolve the issue - let me know if you still see this problem, thanks! I believe it was having the overflow defined.

**Comment by nalmeida** [comment]
The homepage looks fine:
![image](https://user-images.githubusercontent.com/200209/82843335-3d1f0880-9eb3-11ea-938e-95b90021ca3f.png)

But the [documentation page](https://5t3ph.github.io/html-sass-jumpstart/) still with the same issue:
![image](https://user-images.githubusercontent.com/200209/82843370-5a53d700-9eb3-11ea-9fc4-8e0844310ec0.png)

**Comment by 5t3ph** [comment]
Finally got another minute, so the styling one is now updated, too. Thanks!

**Comment by nalmeida** [comment]
Hey @5t3ph, **everything looking fine now**! 
By the way, thanks for sharing this repo!
Closing the issue!

**Comment by 5t3ph** [comment]
Excellent, I appreciate the notice and your follow-up! 🙌
