### ISSUE TITLE
What is the license of this template?

### ISSUE THREAD

**Issue by denisbrodbeck** [5t3ph/11ty-netlify-jumpstart#15]
Hi Stephanie,

thank you for this great template. Could you provide a license for this project?
I'm not sure, whether I'm allowed to clone and derive projects from this template 🤔

**Comment by sophialucero** [comment]
ISC is mentioned here, but confirmation on the homepage/readme would be cool 

```
  "author": "5t3ph",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/5t3ph/11ty-netlify-jumpstart/issues"
  },
``` 

https://github.com/5t3ph/11ty-netlify-jumpstart/blob/main/package.json#L27

**Comment by 5t3ph** [comment]
@denisbrodbeck added a LICENSE.txt with the ISC license text 👍
