### ISSUE TITLE
Starter Blog

### ISSUE THREAD

**Issue by nsmsn** [5t3ph/11ty-netlify-jumpstart#18]
It would be super helpful for beginners like me if this project came with a posts folder with a couple sample posts and a post template (kind of like the eleventy-base-blog starter: https://github.com/11ty/eleventy-base-blog)

**Comment by 5t3ph** [comment]
Hey @nsmsn - thanks for the suggestion, this starter is intentionally lightweight to allow folks to add complexity like that as needed 👍 A similar pattern as is used for the `Pages` would allow extending to a blog type of format :)
