### ISSUE TITLE
Failing at develop process

### ISSUE THREAD

**Issue by rmlumley** [5t3ph/11ty-netlify-jumpstart#4]
I'm getting the following after running npm run develop. I don't receive this error on npm run build.

```
'ELEVENTY_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 11ty-netlify-jumpstart@0.2.0 develop: `npm run scss ; npm run watch:sass & ELEVENTY_ENV=dev npm run watch:eleventy`
npm ERR! Exit status 1
```

**Comment by 5t3ph** [comment]
Thanks @rmlumley, I will look into this!

**Comment by 5t3ph** [comment]
@rmlumley Can you pull in the update I just added to your fork to see if the issue is resolved? Thanks!

**Comment by rmlumley** [comment]
Good news, bad news.

Good: I no longer receive an error. It is watching the sass folder and compiling CSS when I make changes.

Bad: It never serves anything to localhost:8080.

```
C:\Users\rlumley\GitHub\pizzamath>npm run develop

> 11ty-netlify-jumpstart@0.2.1 develop C:\Users\rlumley\GitHub\pizzamath
> npm run scss ; ELEVENTY_ENV=dev eleventy --serve ; npm run watch:eleventy & npm run watch:sass

> 11ty-netlify-jumpstart@0.2.1 scss C:\Users\rlumley\GitHub\pizzamath
> node-sass src/sass -o src/css ";" "ELEVENTY_ENV=dev" "eleventy" ";" "npm" "run" "watch:eleventy"

Rendering Complete, saving .css file...
Wrote CSS to C:\Users\rlumley\GitHub\pizzamath\src\css\social-previews.css
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\rlumley\GitHub\pizzamath\src\css\style.css
Wrote 2 CSS files to C:\Users\rlumley\GitHub\pizzamath\src\css

> 11ty-netlify-jumpstart@0.2.1 watch:sass C:\Users\rlumley\GitHub\pizzamath
> node-sass --watch src/sass -o src/css
```

**Comment by 5t3ph** [comment]
@rmlumley It looks like the develop script didn't update correctly, try swapping for:

```
"develop": "npm run scss ; ELEVENTY_ENV=dev npm run watch:eleventy & npm run watch:sass",
```

**Comment by 5t3ph** [comment]
@rmlumley although it looks like perhaps you're on Windows so the issue maybe that you need to update the package scripts to use something like `npm-run-all` because it seems `&` isn't valid for Windows:

https://www.danvega.dev/blog/2019/04/19/npm-scripts-parallel/

**Comment by rmlumley** [comment]
First off, thanks for looking into this. You are correct that I'm on windows. I'm no expert on npm, but I installed npm-run-all and also made sure I had the correct develop script.

Based on what I read, it seems like I should change it to:

`"develop": "npm run scss ; ELEVENTY_ENV=dev npm-run-all -p watch:eleventy watch:sass",`

When I run it:

```
C:\Users\rlumley\GitHub\pizzamath>npm run develop

> 11ty-netlify-jumpstart@0.2.1 develop C:\Users\rlumley\GitHub\pizzamath
> npm run scss ; ELEVENTY_ENV=dev npm-run-all -p watch:eleventy watch:sass

> 11ty-netlify-jumpstart@0.2.1 scss C:\Users\rlumley\GitHub\pizzamath
> node-sass src/sass -o src/css ";" "ELEVENTY_ENV=dev" "npm-run-all" "watch:eleventy" "watch:sass"

Rendering Complete, saving .css file...
Wrote CSS to C:\Users\rlumley\GitHub\pizzamath\src\css\social-previews.css
Rendering Complete, saving .css file...
Wrote CSS to C:\Users\rlumley\GitHub\pizzamath\src\css\style.css
Wrote 2 CSS files to C:\Users\rlumley\GitHub\pizzamath\src\css
```

Just nothing I does serves anything to localhost. Even if I run eleventy --serve in the command line, I get an error that eleventy is not recognized as an internal or external command.

**Comment by 5t3ph** [comment]
Hi @rmlumley - so sorry, I didn't mean to abandon you! I was hoping to find time to try out changing this to use the `npm-run-all` package. Did you have success? If so, feel free to make PR to add the update!

**Comment by rmlumley** [comment]
Nothing yet on my end, unfortunately.

**Comment by 5t3ph** [comment]
Hi @rmlumley - I've finally had a minute to update this to use `npm-run-all` - please let me know if this resolves your issue! Thank you so much for your patience and alerting me to the issue!

**Comment by rmlumley** [comment]
Sorry I'm late on this but I just tried it and things seem to be working now. Thank you.

**Comment by 5t3ph** [comment]
Great @rmlumley - thanks for confirming!
